@startuml

'Устройство
entity Device {
    +id: uuid
    +name: string
    +connected: boolean
    +active: boolean
    +targetValue: string
    +actualValue: string
    +dateTimeUpdated: timestamptz
    +type_id: uuid <<fk on DeviceType>>
    +user_id: uuid <<fk on User>>
    +device_group_id: uuid <<fk on DeviceGroup>>
}

'Тип устройства
entity DeviceType {
    +id: uuid
    +name: string
    +unit_type: unit <<enum>>
}

'Пользователь
entity User {
    +id: uuid
    +name: string
}

'Местоположение (например, "Дом", "Офис" и т.д.)
entity Location {
    +id: uuid
    +name: string
    +timezone: string
    +user_id: uuid <<fk on user>>
}

'Группа устройств (например, "Гостиная", "Переговорная А" и т.д.)
entity DeviceGroup {
    +id: uuid
    +name: string
    +location_id: uuid <<fk on Location>>
}

'Данные об устройстве в момент времени t
entity TelemetryData {
    +id: uuid
    +dateTime: timestamptz
    +active: boolean
    +value: string
    +unit_type: unit <<enum>>
    +device_id: uuid <<fk on Device>>
}

User }o--|| Device
User }|--|| Location
Location }o--|| DeviceGroup
Device ||--o{ DeviceGroup
Device ||--o{ DeviceType
Device ||--o{ TelemetryData

@enduml