@startuml
%set_variable_value("RELATIVE_INCLUDE", ".")
!include ../C4_Context.puml

Person(user, "Клиент")
Person(engineer, "Выездной специалист", "Подключает новые устройства")
System(warmhouse, "Система «Теплый дом»")
System_Ext(sensor, "Подключенное устройство")

@enduml