@startuml
%set_variable_value("RELATIVE_INCLUDE", ".")
!include ../C4_Context.puml

Person(user, "Клиент")
System(warmhouse, "Система «Теплый дом»")
System_Ext(sensor, "Подключенное устройство")

Rel(user, warmhouse, "Просматривает и управляет устройствами")
Rel(warmhouse, sensor, "Посылает команды")
Rel(sensor, warmhouse, "Обновляет состояние")
Rel(user, sensor, "Регистрирует в системе")

@enduml